// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("350218f8-abca-4295-b8b2-ef27bb3d46ad"),
	Geocodio("acbe3a75-e227-4570-8ad5-a3319ecc4a44"),
	LocationIQ("9ddad79b-8787-43ec-8028-5b14e15a3f18"),
	MapQuest("1e4d97f6-8cb9-4cf0-a86a-10c583e47692");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
