// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("cba99f33-11a7-40f0-9aef-b8cdb484a069"),
	startsWith("cb45c560-848a-4bf9-bfb2-c68538c452b8"),
	endsWith("ebfc361d-ae20-4dd3-8d6d-b8e0df9ceacc"),
	between("f277e1f6-6bc2-4d5f-9b71-df7b8179edd4"),
	greater("548e1406-d98a-4069-b4a5-8d1c1b935c44"),
	greaterEqual("e70343f3-afef-491e-aa28-7fa44f1814c8"),
	equal("339c953c-30b8-4ed0-95a1-27ddd16e80a0"),
	notEqual("8ede18b4-9727-493c-bc1a-e1b392bd203d"),
	smaller("2ed95701-9e72-43ac-88cd-9a2290658418"),
	smallerEqual("e32733cd-b94c-4626-8bca-e512dd402f55"),
	empty("f74360c9-e98c-4b63-a865-73712fdbe579"),
	notEmpty("16c2ffb0-3a40-45fb-9ec0-468a9550cbd0");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
