// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("7344516a-7ed3-4124-9818-0e2e4c06d261"),
	startsWith("012071a9-a095-4a58-96ad-36c979000144"),
	endsWith("7a18ee5c-c784-4f0e-852e-9360c4436de7"),
	between("bc0bfcf8-bce7-4d36-ae48-48bd86151820"),
	greater("1d6c0752-5636-4e20-a070-7e5bc85e02ce"),
	greaterEqual("bfb2fb2b-76f5-4032-ac07-8c05d0374713"),
	equal("4c60b889-ffda-4a46-9ca8-1aeeaf569c41"),
	notEqual("ccd2a3a0-9118-497e-9105-83fe7b93ba1c"),
	smaller("04c1e448-5933-4e0d-a8bd-dfec82d57da3"),
	smallerEqual("290a20b1-070c-4a3e-a99c-6eacbebcebfd"),
	empty("087dde5e-3ad5-4d7e-b5f4-96d8ab5c21c6"),
	notEmpty("54b4e4db-cd53-4dd9-a1c4-518b93f4e59b");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
