// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("30ade257-f000-42cb-88a4-27f855cb05fa"),
	denied("f369d5c7-1864-465d-b8c1-b09c63e5940c"),
	limited("a875edcd-fc59-4ecc-b025-0b9cab61ec2b"),
	granted("8150c1e6-f1c8-461b-8d68-f1f8890fd203"),
	blocked("1bfc1288-5d78-4d4a-ac95-a1e2e9fe6a97");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
