// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("c30977f7-16e6-4199-9ef2-1df27f8c7f83"),
	denied("e6b54a9a-9840-4eb4-94e0-73934ce2790e"),
	limited("a358f531-6316-45e5-ad51-e6fec5078ebb"),
	granted("6697313f-8261-4b86-8687-fa2465d83f46"),
	blocked("37afc7ce-174e-4f92-a86a-38b45027fe76");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
