// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum InAppBrowserDismissButtonStyle
{
	done("5943ae63-4fdd-4af3-98b0-dac5354baf41"),
	close("d9060ca8-f420-45e3-8ae1-5d12615b8e75"),
	cancel("b713fc25-9bfe-484a-ae99-f0ba44777223");

	private final java.lang.String i18nCaptionKey;
	
	private InAppBrowserDismissButtonStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
