// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("e0833a22-9613-4166-836b-ef9233952f13"),
	low("9a51bb7c-a990-4f0c-ac64-4d6647317a77"),
	medium("a3a2fa6c-d707-4c35-b6d1-971c51856583"),
	high("0f40dab6-b0be-4d56-8ff7-9c59fe5c9724"),
	custom("ae6d1c0c-680e-4f33-914b-76116dd8d969");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
