// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("4f3715e5-51c0-4aff-97f3-f94e92653fc1"),
	low("2a9cd3d6-ef55-4bca-b872-72c5d60471b2"),
	medium("f26472f9-126e-4058-9fb7-1cc148b36321"),
	high("de227465-d383-4396-824a-1f314f72e8a8"),
	custom("cc48d36b-ac57-45f8-8dfb-c20a0938ee36");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
